Repository jbosstm/narayana, pull requests merged in 2025-09, with the labels that each got.

#2391 JBTM-4005: Session leak when Synchronization is in aborted state
  ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
  ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/SessionProxy.java
  ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/ConnectionProxyTests.java
  ArjunaJTA/jms/src/test/java/org/jboss/narayana/jta/jms/SessionProxyTests.java
Labels: testing/core

#2401 [JBTM-3997] restat webservice leftover
  rts/at/webservice/pom.xml
Labels: NoCI

#2402 [JBTM-4008] Excluding docs from the release process and link its pom to narayana-all
  docs/pom.xml
  pom.xml
Labels: NoCI

#2409 [JBTM-3997] Some adjustments to which modules are deployed
  ArjunaJTS/orbportability/pom.xml
  XTS/WS-C/pom.xml
  XTS/WS-T/pom.xml
  XTS/WSAS/pom.xml
  XTS/WSCF/pom.xml
  XTS/WSTX/pom.xml
  XTS/bridge/pom.xml
  XTS/pom.xml
  XTS/recovery/pom.xml
  XTS/sar/pom.xml
  pom.xml
Labels: NoCI, testing/core

#2411 [JBTM-3997] vertx removed from the release process
  vertx/pom.xml
Labels: NoCI
